# Inverse encodin/ Inverse transform /Decoding categorical variables

Inverse encoding is the process of converting the encoded data back to its original form. This is done by using the `inverse_transform()` method. This method is available for the following encoders:

- `LabelEncoder`
- `OrdinalEncoder`
- `OneHotEncoder`

In [35]:
# import libraries
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [36]:
# load the data
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [37]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [38]:
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [39]:
# Impute missing values by explicit reassignment (100% reliable)
df['age'] = df['age'].fillna(df['age'].median())
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

# Drop the column and reassign the dataframe
df = df.drop(columns=['deck'], errors='ignore')

# Verify that missing values are gone
print(df[['age', 'embarked', 'embark_town']].isnull().sum())

age            0
embarked       0
embark_town    0
dtype: int64

In [40]:
df.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [41]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [42]:
# encode all categorical variables and object variables

le_sex = LabelEncoder()  # le for label encoder separately for each column
le_embarked = LabelEncoder()
le_class = LabelEncoder()
le_who = LabelEncoder()
le_embark_town = LabelEncoder()
le_alive = LabelEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])
df['class'] = le_class.fit_transform(df['class'])
df['who'] = le_who.fit_transform(df['who'])
df['embark_town'] = le_embark_town.fit_transform(df['embark_town'])
df['alive'] = le_alive.fit_transform(df['alive'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [43]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.0,0,0,13.0000,2,1,1,True,2,0,True
887,1,1,0,19.0,0,0,30.0000,2,0,2,False,2,1,True
888,0,3,0,28.0,1,2,23.4500,2,2,2,False,2,0,False
889,1,1,1,26.0,0,0,30.0000,0,0,1,True,0,1,True
890,0,3,1,32.0,0,0,7.7500,1,2,1,True,1,0,True

In [44]:
# inverse transform the data

df['sex'] = le_sex.inverse_transform(df['sex'])
df['embarked'] = le_embarked.inverse_transform(df['embarked'])
df['class'] = le_class.inverse_transform(df['class'])
df['who'] = le_who.inverse_transform(df['who'])
df['embark_town'] = le_embark_town.inverse_transform(df['embark_town'])
df['alive'] = le_alive.inverse_transform(df['alive'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [45]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

# one hot encoding

In [47]:
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Load data
df = sns.load_dataset('titanic')

# Crucial: Impute missing values first (otherwise encoder creates a 'NaN' column)
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

cat_columns = ['sex', 'embarked']

# Use 'sparse_output=False' for newer sklearn versions (>= 1.2)
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Transform and extract proper feature names for columns
encoded_array = encoder.fit_transform(df[cat_columns])
encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(cat_columns))

# Concatenate the dataframes vertically matching indices
df = pd.concat([df, encoded_df], axis=1)

# Drop original categorical columns to avoid duplicate information
df.drop(columns=cat_columns, inplace=True)

print(df.head())

   survived  pclass   age  sibsp  parch     fare  class    who  adult_male  \
0         0       3  22.0      1      0   7.2500  Third    man        True
1         1       1  38.0      1      0  71.2833  First  woman       False
2         1       3  26.0      0      0   7.9250  Third  woman       False
3         1       1  35.0      1      0  53.1000  First  woman       False
4         0       3  35.0      0      0   8.0500  Third    man        True

  deck  embark_town alive  alone  sex_female  sex_male  embarked_C  \
0  NaN  Southampton    no  False         0.0       1.0         0.0
1    C    Cherbourg   yes  False         1.0       0.0         1.0
2  NaN  Southampton   yes   True         1.0       0.0         0.0
3    C  Southampton   yes  False         1.0       0.0         0.0
4  NaN  Southampton    no   True         0.0       1.0         0.0

   embarked_Q  embarked_S
0         0.0         1.0
1         0.0         0.0
2         0.0         1.0
3         0.0         1.0
4         0.0         1.0

In [ ]:
df   # the best is label encoding

,survived,pclass,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S
0,0,3,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False,0.0,1.0,0.0,0.0,1.0
1,1,1,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False,1.0,0.0,1.0,0.0,0.0
2,1,3,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True,1.0,0.0,0.0,0.0,1.0
3,1,1,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False,1.0,0.0,0.0,0.0,1.0
4,0,3,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,Second,man,True,NaN,Southampton,no,True,0.0,1.0,0.0,0.0,1.0
887,1,1,19.0,0,0,30.0000,First,woman,False,B,Southampton,yes,True,1.0,0.0,0.0,0.0,1.0
888,0,3,NaN,1,2,23.4500,Third,woman,False,NaN,Southampton,no,False,1.0,0.0,0.0,0.0,1.0
889,1,1,26.0,0,0,30.0000,First,man,True,C,Cherbourg,yes,True,0.0,1.0,1.0,0.0,0.0
890,0,3,32.0,0,0,7.7500,Third,man,True,NaN,Queenstown,no,True,0.0,1.0,0.0,1.0,0.0

In [49]:
# We need to extract the original categories for each encoded column
original_categories = {col: encoder.categories_[i] for i, col in enumerate(cat_columns)}
# Manual creation of feature names
feature_names = []
for i, col in enumerate(cat_columns):
    for category in encoder.categories_[i]:
        feature_names.append(f"{col}_{category}")

encoded_df = pd.DataFrame(encoded_df, columns=feature_names)

df.head()

,survived,pclass,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S
0,0,3,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False,0.0,1.0,0.0,0.0,1.0
1,1,1,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False,1.0,0.0,1.0,0.0,0.0
2,1,3,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True,1.0,0.0,0.0,0.0,1.0
3,1,1,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False,1.0,0.0,0.0,0.0,1.0
4,0,3,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True,0.0,1.0,0.0,0.0,1.0

# Assignment: Use Ordinal Encoder with Inverse Transform Method.